task-name = "cdc-task00"
datasource-name-s = "tidb85"
datasource-name-t = "ora151"
comment = "测试数据源"

[case-field-rule]
# 控制配置文件内所有 *-s 参数配置值以及 column-route-rules 中的 key 值
# 1，参数值是 0 代表以当前配置文件为准，与源端对比
# 2，参数值是 1 代表统一转换值为小写，与源端对比
# 3，参数值是 2 代表统一转换值为大写，与源端对比
case-field-rule-s = "0"
# 控制配置文件 *-t 以及 column-route-rules 中的 value 值
# 1，参数值是 0 代表统一转换数据库名、表名、字段名值以当前配置文件为准
# 2，参数值是 1 代表统一转换数据库名、表名、字段名值为小写
# 3，参数值是 2 代表统一转换数据库名、表名、字段名值为大写
case-field-rule-t = "2"

[schema-route-rule]
schema-name-s = "marvin"
schema-name-t = "MARVIN"
# include-table-s 迁移所有表需指定 "*"，特定表写具体表名
#include-table-s = ["MARVIN00","MARVIN01","MARVIN05","MARVIN_COLUMN_T"]
include-table-s = ["*"]
#include-table-s = ["MARVIN00","MARVIN01","MARVIN05"]
#include-table-s = ["PM_TC_PROCESS_CODE","MARVIN00","MARVIN01"]
exclude-table-s = []

[[schema-route-rule.table-route-rules]]
table-name-s = ""
table-name-t = ""
column-route-rules = {}

[cdc-consume-param]
server-address = ["120.92.108.85:54323","120.92.108.85:54323","120.92.108.85:54323"]
subscribe-topic = "cdc_marvin_topic"
table-thread = 10
# 参考上游数据是否开启压缩，设置对应压缩算法
# 可选值有 "none"、"lz4"、"snappy"，默认为 "none"
message-compression = "none"
# ticdc 数据同步
# 避免由于 resolvedTs 前无数据而导致频繁刷新元数据，检查 <=resolvedTs 前是否有数据
# 如果有数据，则立即刷新，如果连续 X seconds resolvedT 没有数据，则达到 X seconds resolvedT 时再刷新
# 单位：seconds
idle-resolved-threshold = 60
# calltimeout，单位：秒
call-timeout = 36000
enable-checkpoint = true
# ticdc 不支持虚拟生成列的数据表同步，可能会引入上下游数据一致性问题，但支持存储 store 生成列的数据表同步
# 对于 store 生成列同步，根据参数 enable-virtual-column 配置是否进行数据同步
# 当下游表同样存在 virtual column，建议设置 false 即下游自动根据表达式自动计算生成，默认值 false
# 当下游表不存在 virtual column，而使用普通数据类型代替，则建议设置 true，自适应下游数据类型调整同步消费
enable-virtual-column = false