task-name = "dct_33to45"
datasource-name-s = "oracle33"
datasource-name-t = "tidb145"
comment = "测试数据源"

[case-field-rule]
# 控制配置文件内所有 *-s 参数配置值以及 column-route-rules 中的 key 值
# 1，参数值是 0 代表以当前配置文件为准，与源端对比
# 2，参数值是 1 代表统一转换值为小写，与源端对比
# 3，参数值是 2 代表统一转换值为大写，与源端对比
case-field-rule-s = "0"
# 控制配置文件 *-t 以及 column-route-rules 中的 value 值
# 1，参数值是 0 代表统一转换数据库名、表名、字段名值以当前配置文件为准
# 2，参数值是 1 代表统一转换数据库名、表名、字段名值为小写
# 3，参数值是 2 代表统一转换数据库名、表名、字段名值为大写
case-field-rule-t = "0"

[schema-route-rule]
schema-name-s = "MARVIN"
schema-name-t = "STEVEN"
include-table-s = ["MARVIN_COLUMN_T"]
#include-table-s = ["MARVIN00","MARVIN01","MARVIN05"]
#include-table-s = ["PM_TC_PROCESS_CODE","MARVIN00","MARVIN01"]
exclude-table-s = []
#exclude-table-s = ["P4","WUCHAO_TEST_BLOB"]

[[schema-route-rule.table-route-rules]]
table-name-s = "MARVIN00"
table-name-t = "STEVEN00"
column-route-rules = {"NAME" = "T_NAME00"}
[[schema-route-rule.table-route-rules]]
table-name-s = "MARVIN01"
table-name-t = "STEVEN01"
column-route-rules = {"NAME" = "t_name00"}

[[data-compare-rules]]
table-name-s = ""
compare-field = ""
# 指定检查数据范围或者查询条件
# range 优先级高于 column-field
compare-range = ""
# 忽略对比字段列
ignore-fields = []

# 表串行运行，表内并发
[data-compare-param]
# 初始化表任务并发数
table-thread = 100
# 数据写入批量大小
batch-size = 50
# 表内 SQL 执行并发数，表示同时多少并发 SQL 读取上下游表数据，可动态变更
sql-thread = 2
# 指定分片 chunk sql 查询 hint
sql-hint-s = "/*+ PARALLEL(8) */"
# 指定分片 chunk sql 查询 Hint
sql-hint-t = ""
only-compare-row = false
# calltimeout，单位：秒
call-timeout = 36000
enable-checkpoint = true
# 是否一致性读 ORA（自动获取上游当前的 SCN 一致性读）
enable-consistent-read = false
# 一致性读 point（手工配置上下游一致性 point）
# consistent-read-point-s 参数生效 Only enable-consistent-read = false，如果是 enable-consistent-read = true，则自动获取上游当前的 SCN 为准
consistent-read-point-s = ""
# consistent-read-point-t 参数 mysql 数据库不支持指定配置，自动忽略配置，tidb 数据库支持
consistent-read-point-t = ""