[[datasource]]
datasource-name = "oracle33"
db-type = "oracle"
username = "findpt"
password = "findpt"
host = "10.2.103.33"
port = 1521
connect-charset = "zhs16gbk"
connect-params = ""
service-name = "gbk"
#pdb-name = ""
[[datasource]]
datasource-name = "tidb145"
db-type = "tidb"
username = "root"
password = ""
host = "120.92.77.145"
port = 4000
connect-charset = "utf8mb4"
#connect-params = ""
#service-name = ""
#pdb-name = ""