task-name = "scmt_33to45"
datasource-name-s = "oracle33"
datasource-name-t = "tidb145"
comment = "测试数据源"

[struct-compare-param]
compare-thread = 10
enable-checkpoint = true
# calltimeout，单位：秒
call-timeout = 36000

[case-field-rule]
# 控制配置文件内所有 *-s 参数配置值（default-value-s 除外）以及 column-route-rules 中的 key 值
# 1，参数值是 0 代表以当前配置文件为准，与源端对比
# 2，参数值是 1 代表统一转换值为小写，与源端对比，default-value-s 参数配置始终以参数配置大小为准与源端对比
# 3，参数值是 2 代表统一转换值为大写，与源端对比，default-value-s 参数配置始终以参数配置大小为准与源端对比
case-field-rule-s = "0"
# 控制配置文件 schema-name-t、table-name-t 以及 column-route-rules 中的 value 值，、column-type-t/table-attrs-t 不受控制默认大写
# 1，参数值是 0 代表统一转换数据库名、表名、字段名值以当前配置文件为准，非配置文件配置的以上游为准
# 2，参数值是 1 代表统一转换数据库名、表名、字段名值为小写，default-value-t 参数配置始终以参数配置大小为准与源端对比
# 3，参数值是 2 代表统一转换数据库名、表名、字段名值为大写，default-value-t 参数配置始终以参数配置大小为准与源端对比
case-field-rule-t = "0"


[schema-route-rule]
schema-name-s = "MARVIN"
schema-name-t = "STEVEN"
include-table-s = ["MARVIN00","MARVIN01","MARVIN05","MARVIN_COLUMN_T"]
exclude-table-s = []

[[schema-route-rule.table-route-rules]]
table-name-s = "MARVIN00"
table-name-t = "STEVEN00"
column-route-rules = {"NAME" = "T_NAME00"}
[[schema-route-rule.table-route-rules]]
table-name-s = "MARVIN01"
table-name-t = "STEVEN01"
column-route-rules = {"NAME" = "t_name00"}

# 默认值规则设置分为字符类型 OR 数值类型 OR 函数表达式 OR '' 空字符串 OR NULL 字符
# 字符类型设置需要带单引号
# 数值类型以及函数表达式设置保持本身即可
# 对于 N01 VARCHAR2(10) DEFAULT '' 设置映射，以 '' 设置代替
# 对于 N01 VARCHAR2(10) DEFAULT 'Null' 设置映射，以 'Null' 设置代替
# 对于 N01 VARCHAR2(10) DEFAULT NULL 设置 NULL 映射，以 NULL 设置代替
# 对于 N01 VARCHAR2(10) 字段设置 NULL 映射，以 NULLSTRING 设置代替
[struct-compare-rule]
[[struct-compare-rule.task-struct-rules]]
column-type-s = "NUMBER(38)"
column-type-t = "BIGINT"
default-value-s = "5"
default-value-t = "10"
[[struct-compare-rule.schema-struct-rules]]
schema-name-s = "MARVIN"
column-type-s = "NUMBER"
column-type-t = "BIGINT"
default-value-s = ""
default-value-t = ""
[[struct-compare-rule.table-struct-rules]]
schema-name-s = "MARVIN"
table-name-s = "MARVIN00"
column-type-s = "NUMBER"
column-type-t = "BIGINT(20)"
default-value-s = "'pw'"
default-value-t = "'pc'"
[[struct-compare-rule.column-struct-rules]]
schema-name-s = "MARVIN"
table-name-s = "MARVIN00"
column-name-s = "ID"
column-type-s = "NUMBER"
column-type-t = "INT"
default-value-s = ""
default-value-t = ""
[[struct-compare-rule.column-struct-rules]]
schema-name-s = "MARVIN"
table-name-s = "MARVIN01"
column-name-s = "XF"
column-type-s = ""
column-type-t = ""
default-value-s = "''"
default-value-t = "'STRING'"
[[struct-compare-rule.column-struct-rules]]
schema-name-s = "MARVIN"
table-name-s = "MARVIN01"
column-name-s = "XFO"
column-type-s = ""
column-type-t = ""
default-value-s = "NULLSTRING"
default-value-t = "'pingcap'"
[[struct-compare-rule.column-struct-rules]]
schema-name-s = "MARVIN"
table-name-s = "MARVIN01"
column-name-s = "XFT"
column-type-s = ""
column-type-t = ""
default-value-s = "NULL"
default-value-t = "'marvin'"


