task-rule-name = "oracle33totidb145_rule"
datasource-name-s = "oracle33"
datasource-name-t = "tidb145"
comment = "测试数据源"

[[schema-route-rules]]
source-schema = "findpt"
target-schema = "steven"

source-include-table = []
source-exclude-table = []

[[schema-route-rules.table-route-rules]]
source-table = "marvin00"
target-table = "steven00"
column-route-rules = {"name" = "s_name00"}
[[schema-route-rules.table-route-rules]]
source-table = "marvin01"
target-table = "steven02"
column-route-rules = {"i01" = "s_i01", "i02" = "s_i02"}