style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: github.com/wentaojin/dbms
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - chore
        - docs
        - style
        - test
        - revert
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Chores
      docs: Documentation Changes
      style: Code Style Changes
      test: Tests
      revert: Reverts
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE