[worker]
endpoint = "192.168.0.101:2379,192.168.0.101:3379,192.168.0.101:4379"
worker-addr = "192.168.0.101:8261"
keepalive-ttl = 30
event-queue-size = 1024

[log]
log-level = "info"
log-file = "/Users/wentaojin/gostore/dbms/data/dbms-worker-8261.log"
max-size = 128
max-days = 7
max-backups = 30