style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: github.com/wentaojin/dbms
options:
  tag_filter_pattern: '^v'
  sort: "date"
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Styles
      docs: Documentation
      chore: Chore
      revert: Revert
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE